apiVersion: v2
name: infra
description: A Helm Chart for Teknoir infrastructure components
type: application
version: 0.2.0
appVersion: "1.0.0"
dependencies:
  - name: teknoir-gateway
    version: 0.0.2
    repository: "file://../teknoir-gateway"
    condition: teknoir-gateway.enabled
  - name: auth
    version: 0.0.2
    repository: "file://../auth"
    condition: auth.enabled
  - name: harbor
    version: 0.0.2
    repository: "file://../harbor"
    condition: harbor.enabled
