---
apiVersion: v1
kind: Namespace
metadata:
  name: teknoir-bootstrap
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: infra-stage-0
  namespace: teknoir-bootstrap
spec:
  repo: https://teknoir.github.io/infra
  chart: infra-stage-0
  version: 0.1.6
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    # Example for minimal configuration
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: infra-stage-1
  namespace: teknoir-bootstrap
spec:
  repo: https://teknoir.github.io/infra
  chart: infra-stage-1
  version: 0.1.6
  targetNamespace: istio-system
  valuesContent: |-
    # Example for minimal configuration
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: infra-stage-2
  namespace: teknoir-bootstrap
spec:
  repo: https://teknoir.github.io/infra
  chart: infra-stage-2
  version: 0.1.6
  targetNamespace: istio-system
  valuesContent: |-
    # Example for minimal configuration
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: infra-stage-2b
  namespace: teknoir-bootstrap
spec:
  repo: https://teknoir.github.io/infra
  chart: infra-stage-2b
  version: 0.1.6
  targetNamespace: istio-system
  valuesContent: |-
    # Example for minimal configuration
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: infra-stage-3
  namespace: teknoir-bootstrap
spec:
  repo: https://teknoir.github.io/infra
  chart: infra-stage-3
  version: 0.1.6
  targetNamespace: istio-system
  valuesContent: |-
    # Example for minimal configuration
