---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-egressgateway
  namespace: kube-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: gateway
  targetNamespace: istio-system
  createNamespace: true
  takeOwnership: true
  valuesContent: |-
    name: istio-egressgateway
    labels:
      istio: egressgateway
    service:
      type: ClusterIP
