---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: teknoir-system
spec:
  sourceRepos:
    - '*'
  sourceNamespaces: []
  destinations:
    - namespace: 'teknoir-system'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: 'argoproj.io'
      kind: 'AppProject'
    - group: 'argoproj.io'
      kind: 'Application'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: teknoir-system
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/app-of-apps
    repoURL: https://github.com/teknoir/platform-applications-gitops
    targetRevision: teknoir-cloud
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
