apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "auth.teknoir.online"
  gateways:
    - istio-system/teknoir-gateway
  http:
    - name: keycloak
      route:
        - destination:
            host: {{ .Values.keycloak.service.name | default (printf "%s-http" .Values.keycloak.fullnameOverride) }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.keycloak.service.httpPort }}
