apiVersion: v2
name: stage-8-harbor
description: Infra stage 8 - Harbor
type: application
version: 0.0.2
appVersion: "2.12.0"
dependencies:
  - name: harbor
    version: ">=1.16.0 <1.17.0"
    repository: https://helm.goharbor.io
