# Default values for teknoir-gateway.
namespace: istio-system
domain: ""
hosts: []
tls:
  credentialName: ""

letsencrypt:
  email: ""
  server: https://acme-v02.api.letsencrypt.org/directory
  cloudDNS:
    project: "teknoir"
    serviceAccountSecretRef:
      name: "clouddns-dns01"
      key: key.json
  certificate:
    commonName: ""
    dnsNames: []
    secretName: ""

  # Can be clouddns, godaddy, loopia
  solver: godaddy