---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istiod
  namespace: kube-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: istiod
  targetNamespace: istio-system
  createNamespace: true
  takeOwnership: true
  valuesContent: |-
    global:
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi