{{- if .Values.httpbin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: httpbin
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: {{ .Values.httpbin.image.repository }}:{{ .Values.httpbin.image.tag }}
          ports:
            - name: http
              containerPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
{{- range .Values.httpbin.virtualService.hosts }}
  - {{ . | quote }}
{{- end }}
  gateways:
    - istio-system/teknoir-gateway
  http:
    - route:
        - destination:
            host: httpbin.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
{{- end -}}
