---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: teknoir-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
{{- range .Values.hosts }}
    - {{ . | quote }}
{{- end }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
{{- range .Values.hosts }}
    - {{ . | quote }}
{{- end }}
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.tls.credentialName | quote }}

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: teknoir-gateway-public
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway-public
  servers:
    - port:
        name: tls-mqtt
        number: 8883
        protocol: TLS
      hosts:
{{- range .Values.hosts }}
        - {{ . | quote }}
{{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.tls.credentialName | quote }}
    - port:
        name: https-mqtt
        number: 8084
        protocol: HTTPS
      hosts:
{{- range .Values.hosts }}
        - {{ . | quote }}
{{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.tls.credentialName | quote }}
    - port:
        name: tls-ssh
        number: 2222
        protocol: TLS
      hosts:
{{- range .Values.hosts }}
        - {{ . | quote }}
{{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.tls.credentialName | quote }}
