---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager-webhook-godaddy
  namespace: kube-system
spec:
  repo: https://snowdrop.github.io/godaddy-webhook
  chart: godaddy-webhook
  targetNamespace: cert-manager
  createNamespace: true
  takeOwnership: true
  valuesContent: |-
    groupName: acme.webhook.godaddy.com

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: {{ .Values.letsencrypt.email | quote }}
    server: {{ .Values.letsencrypt.server | quote }}
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - selector:
          dnsZones:
            - "teknoir.online"
        dns01:
          webhook:
            groupName: acme.webhook.godaddy.com
            solverName: godaddy
            config:
              apiKeySecretRef:
                name: godaddy-api-key-prod
                key: token
              production: true
              ttl: 600