# Default values for infra-stage-5.
hosts:
  - "teknoir.online"
  - "*.teknoir.online"
tls:
  credentialName: teknoir-online-wildcard-tls

letsencrypt:
  email: admin@teknoir.online
  server: https://acme-v02.api.letsencrypt.org/directory
  cloudDNS:
    project: "teknoir"
    serviceAccountSecretRef:
      name: "clouddns-dns01"
      key: key.json
  certificate:
    commonName: "*.teknoir.online"
    dnsNames:
      - "*.teknoir.online"
      - "teknoir.online"
    secretName: teknoir-online-wildcard-tls